# -*- coding: utf-8 -*-
# Deployment settings for AIMessage.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.2/s3e/makefile_builder/mkb.py', 'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/AIMessage.mkb', '--default-buildenv=vc10', '--msvc-project', '--deploy-only']
mkb = 'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/AIMessage.mkb'
mkf = ['c:\\marmalade\\6.2\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.2\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.2\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.2\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\dizzi\\appdata\\roaming\\marmalade\\packages\\6.2.0\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\dizzi\\appdata\\roaming\\marmalade\\packages\\6.2.0\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\dizzi\\appdata\\roaming\\marmalade\\packages\\6.2.0\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.2\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.2\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.2\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\dizzi\\appdata\\roaming\\marmalade\\packages\\6.2.0\\tiniconv_1.0.1\\tiniconv.mkf', 'e:\\4410-5-1-13\\team-game-4410\\game source\\aimessage\\tinyxml.mkf', 'c:\\marmalade\\6.2\\modules\\iwui\\iwui.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data-ram/data-gles1/fonts.group.bin,e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data/fonts.group.bin', 'fonts.group.bin', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data-ram/data-gles1/font.gxfont.bin,e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data/font.gxfont.bin', 'font.gxfont.bin', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data-ram/data-gles1/ui.group.bin,e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data/ui.group.bin', 'ui.group.bin', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data-ram/data-gles1/IwUIBasicLabelCode.group.bin,e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data/IwUIBasicLabelCode.group.bin', 'IwUIBasicLabelCode.group.bin', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data-ram/rickhistory.xml', 'rickhistory.xml', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data-ram/ReplyOptions.xml', 'ReplyOptions.xml', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data-ram/rick.xml', 'rick.xml', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data/txtButton_small.png', 'txtButton_small.png', 0),
    ('e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data/dialogue.xml', 'dialogue.xml', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'AIMessage'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'AIMessage'
    long_caption = 'AIMessage'
    version = [0, 0, 1]
    config = ['e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data/app.icf']
    data_dir = 'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    iphone_appid = 'AIMessage'
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Debug_AIMessage_VC10_arm/AIMessage.s3e',
                   'release' : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Release_AIMessage_VC10_arm/AIMessage.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Debug_AIMessage_VC10_gcc_mips/AIMessage.so',
                   'release' : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Release_AIMessage_VC10_gcc_mips/AIMessage.so',
                 },
         'x86' : {
                   'debug'   : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Debug_AIMessage_VC10_x86/AIMessage.s86',
                   'release' : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Release_AIMessage_VC10_x86/AIMessage.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Debug_AIMessage_VC10_gcc_arm/AIMessage.s3e',
                   'release' : r'e:/4410-5-1-13/team-game-4410/Game Source/AIMessage/build_aimessage_vc10/Release_AIMessage_VC10_gcc_arm/AIMessage.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
